links:
  railstutorial: "https://www.railstutorial.org/"
  learnenough: "https://www.learnenough.com/"
  railstutorial_help: "https://www.railstutorial.org/help"
  gravatar: "https://www.gravatar.com/avatar/"
validations:
  users:
    email_regex: !ruby/regexp "/\\A[\\w+\\-.]+@[a-z\\d\\-]+(\\.[a-z\\d\\-]+)*\\.[a-z]+\\z/i"
    name_max_length: 50
    email_max_length: 255
    password_min_length: 6
