links:
  railstutorial: "https://www.railstutorial.org/"
  learnenough: "https://www.learnenough.com/"
  railstutorial_help: "https://www.railstutorial.org/help"
  gravatar: "https://www.gravatar.com/avatar/"
  gravatar_email: "https://gravatar.com/emails"
  img_logo: "rails.png"
validations:
  users:
    email_regex: !ruby/regexp "/\\A[\\w+\\-.]+@[a-z\\d\\-]+(\\.[a-z\\d\\-]+)*\\.[a-z]+\\z/i"
    name_max_length: 50
    email_max_length: 255
    password_min_length: 6
    size_avatar: 50
    per_page: 10
    remember: 1
    expire_reset_pass: 2
  post:
    content_length: 144
    size_image: 5
    width_size: 200
    height_size: 100
    content_type_image: /%w(image/jpeg image/gif image/png)/
